### ISSUE TITLE
Handle bookmark folders

### ISSUE THREAD

**Issue by srudisill** [johnnyfreeman/winston#9]
Chrome supports bookmark folders. Maybe list the bookmarks within that folder if the search matches?

**Comment by johnnyfreeman** [comment]
Good catch @srudisill!

My first thought was, when you are typing the name of a bookmark folder, to open that folder. However, the [chrome.bookmarks api](https://developer.chrome.com/extensions/bookmarks) doesn't appear to offer any way to do that.

When I inspect the bookmark result [from here](https://github.com/johnnyfreeman/winston/blob/master/src/js/bookmarks.js#L18), this is what is returned for a _folder_:

```javascript
{
    dateAdded: 1379855896022,
    dateGroupModified: 1416522864648,
    id: "55",
    index: 6,
    parentId: "1",
    title: "Tattoos"
}
```

And this for a child _bookmark_ of that folder:

```javascript
{
    dateAdded: 1379902475572,
    id: "58",
    index: 0,
    parentId: "55",
    title: "full-sleeve-tattoo-designs",
    url: "http://tattooideasmag.com/extreme-full-sleeve-tattoos/full-sleeve-tattoo-designs/"
}
```

So what is the proper way to handle a query for a folder? It seems like the options are to either:

a) Not include bookmark results where `bookmark.url` is `undefined`.
b) Do another (nested) search query for all the child bookmarks where `child.parentId` == `parent.id`

I go back and forth. On one hand, a package should try to give you the most accurate/relevant results matching your input string. So returning the children of what you're looking seems contradictory to that idea. On the other hand, I think it _should_ be left up the the package itself to determine what _is_ accurate or relevant to your input string.

Thoughts?

**Comment by srudisill** [comment]
You could search the children with the remaining search terms that didn’t match the parent.

**Comment by johnnyfreeman** [comment]
Something that should also be considered here is how Winston handles [bookmarklets](http://en.wikipedia.org/wiki/Bookmarklet).

**Comment by johnnyfreeman** [comment]
Since the APIs aren't mature enough (yet) to handle bookmark folders (or bookmarklets), they will not show up in the results.
